GET http://localhost:8000/api/auth


###

POST http://localhost:8000/api/auth
Content-Type: application/json

{
  "name": "Hiba",
  "password": "password"
}
###
POST http://localhost:8000/api/auth
Content-Type: application/json

{
  "name": "Hiba",
  "password": "passw"
} 
###
POST http://localhost:8000/api/auth/localhost:8000/register

Content-Type: application/json
{
  "name": "Hiba",
  "password": "passw"
} 
